---
- name: Gather EC2 instance metadata
  action: ec2_metadata_facts
- name: Start application
  command: wget "http://{{tomcat_user}}:{{tomcat_pwd}}@{{ansible_ec2_public_ipv4}}:8090/manager/text/start?path=/webapp" -O - -q
